apiVersion: skaffold/v4beta1
kind: Config
metadata:
  name: router
build:
  artifacts:
    - image: lcacollect/rover
      context: ./
      docker:
        dockerfile: ./Dockerfile
manifests:
  helm:
    releases:
      - name: router
        chartPath: ./helm
        namespace: router
        setValues:
          clientOrigin: http://localhost:4200
          deployType: DEV
          imageKey.registry: lcacollect/rover
          imageKey.repository: lcacollect/rover
          imageKey.tag: lcacollect/rover
        setValueTemplates:
          secretStore.tenantId: '{{ .AAD_TENANT_ID }}'
          secretStore.userAssignedIdentityID: '{{ .AAD_APP_CLIENT_ID }}'
        createNamespace: true
deploy:
  helm: { }
portForward:
  - resourceType: service
    resourceName: router-service
    namespace: router
    port: 4000
