{{- if eq .Values.deployType "PROD"}}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.secretName }}
  namespace: {{ .Values.namespace }}
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: {{ .Values.secretStore.userAssignedIdentityID }}
    tenantID: {{ .Values.secretStore.tenantId }}
    keyvaultName: {{ .Values.secretStore.name }}
    objects: |
      array:
        - |
          objectName: {{ .Values.tlsSecret }}
          objectType: secret
  secretObjects:
    - data:
      - key: tls.key
        objectName: {{ .Values.tlsSecret }}
      - key: tls.crt
        objectName: {{ .Values.tlsSecret }}
      secretName: {{ .Values.tlsSecret }}
      type: kubernetes.io/tls
# Sources:
# https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-identity-access
# https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver#validate-the-secrets
# https://docs.microsoft.com/en-us/azure/aks/csi-secrets-store-driver
{{- end }}