server:
  endpoint: /graphql
  listen: 0.0.0.0:4000
  landing_page: true # playground for the gateway
  cors:
    origins: # Specific Origin required with allow credentials set to true.
      - ${CLIENT_ORIGIN:http://localhost:3000}
      - https://doc.arkitema.com
    allow_credentials: true
headers:
  all: # Header rules for all subgraphs
    - propagate: # send the following matching headers onwards from the client to all subgraphs
        matching: authorization
    - propagate:
        matching: origin # required for member invitation to indicate platform where invite originates
plugins:
  experimental.include_subgraph_errors:
    all: true
override_subgraph_url:
  project: ${PROJECT_URL:http://localhost:5000}
  documentation: ${DOCUMENTATION_URL:http://localhost:5002}
